name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 8.0, 8.1 ]
        laravel: [ 9.* ]
        stability: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer install -q --no-progress --prefer-dist --no-interaction --no-suggest --optimize-autoloader --no-scripts


      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          ZAMMAD_URL: ${{ secrets.ZAMMAD_URL }}
          ZAMMAD_TOKEN: ${{ secrets.ZAMMAD_TOKEN }}

      - name: Store test reports
        uses: actions/upload-artifact@v2
        with:
          name: Store report
          retention-days: 1
          path: |
            ./reports
